import type { PersonalityQuestion } from '../types';

const koOptions = (axis: 'ANX' | 'AVO') => [
  { id: 'A' as const, text: '전혀 아니다', scores: { [axis]: 0 } },
  { id: 'B' as const, text: '별로 아니다', scores: { [axis]: 1 } },
  { id: 'C' as const, text: '약간 그렇다', scores: { [axis]: 2 } },
  { id: 'D' as const, text: '매우 그렇다', scores: { [axis]: 3 } },
];

const enOptions = (axis: 'ANX' | 'AVO') => [
  { id: 'A' as const, text: 'Not at all', scores: { [axis]: 0 } },
  { id: 'B' as const, text: 'Rarely', scores: { [axis]: 1 } },
  { id: 'C' as const, text: 'Somewhat', scores: { [axis]: 2 } },
  { id: 'D' as const, text: 'Very much', scores: { [axis]: 3 } },
];

export const attachmentQuestionsKo: PersonalityQuestion[] = [
  {
    id: 'at-ko-01',
    order_index: 1,
    locale: 'ko',
    question_text: '연인이 나를 떠나거나 마음이 식을까 봐 자주 불안하다.',
    options: koOptions('ANX'),
  },
  {
    id: 'at-ko-02',
    order_index: 2,
    locale: 'ko',
    question_text: '상대가 나를 정말 사랑하는지 자꾸 확인받고 싶어진다.',
    options: koOptions('ANX'),
  },
  {
    id: 'at-ko-03',
    order_index: 3,
    locale: 'ko',
    question_text: '연락이 늦거나 답장이 없으면 머릿속이 온통 그 생각으로 가득 찬다.',
    options: koOptions('ANX'),
  },
  {
    id: 'at-ko-04',
    order_index: 4,
    locale: 'ko',
    question_text: '상대가 보낸 메시지의 말투나 단어 하나하나를 곱씹으며 의미를 분석한다.',
    options: koOptions('ANX'),
  },
  {
    id: 'at-ko-05',
    order_index: 5,
    locale: 'ko',
    question_text: '내가 상대를 좋아하는 만큼 상대는 나를 좋아하지 않는 것 같아 서운하다.',
    options: koOptions('ANX'),
  },
  {
    id: 'at-ko-06',
    order_index: 6,
    locale: 'ko',
    question_text: '연인이 다른 사람에게 관심을 보이면 쉽게 질투가 난다.',
    options: koOptions('ANX'),
  },
  {
    id: 'at-ko-07',
    order_index: 7,
    locale: 'ko',
    question_text: '혼자 있으면 관계에 무슨 문제가 있는 건 아닐까 걱정하게 된다.',
    options: koOptions('ANX'),
  },
  {
    id: 'at-ko-08',
    order_index: 8,
    locale: 'ko',
    question_text: '사소한 다툼에도 관계가 끝나버릴까 봐 마음이 크게 흔들린다.',
    options: koOptions('ANX'),
  },
  {
    id: 'at-ko-09',
    order_index: 9,
    locale: 'ko',
    question_text: '연인과 너무 가까워지면 오히려 답답하고 부담스럽게 느껴진다.',
    options: koOptions('AVO'),
  },
  {
    id: 'at-ko-10',
    order_index: 10,
    locale: 'ko',
    question_text: '관계가 진지해질 기미가 보이면 나도 모르게 거리를 두게 된다.',
    options: koOptions('AVO'),
  },
  {
    id: 'at-ko-11',
    order_index: 11,
    locale: 'ko',
    question_text: '내 속마음이나 약한 모습을 상대에게 털어놓는 것이 어렵다.',
    options: koOptions('AVO'),
  },
  {
    id: 'at-ko-12',
    order_index: 12,
    locale: 'ko',
    question_text: '연애를 하더라도 나만의 독립적인 시간과 공간이 꼭 필요하다.',
    options: koOptions('AVO'),
  },
  {
    id: 'at-ko-13',
    order_index: 13,
    locale: 'ko',
    question_text: '누군가에게 의지하기보다 혼자 해결하는 편이 마음이 편하다.',
    options: koOptions('AVO'),
  },
  {
    id: 'at-ko-14',
    order_index: 14,
    locale: 'ko',
    question_text: '상대가 감정적으로 너무 많은 것을 요구하면 한 발 물러서고 싶어진다.',
    options: koOptions('AVO'),
  },
  {
    id: 'at-ko-15',
    order_index: 15,
    locale: 'ko',
    question_text: '관계의 깊은 감정 이야기보다는 가볍고 편안한 분위기를 선호한다.',
    options: koOptions('AVO'),
  },
  {
    id: 'at-ko-16',
    order_index: 16,
    locale: 'ko',
    question_text: '연인이 내 일상에 너무 깊이 들어오면 자유를 잃는 기분이 든다.',
    options: koOptions('AVO'),
  },
];

export const attachmentQuestionsEn: PersonalityQuestion[] = [
  {
    id: 'at-en-01',
    order_index: 1,
    locale: 'en',
    question_text: 'I often worry that my partner will leave me or stop loving me.',
    options: enOptions('ANX'),
  },
  {
    id: 'at-en-02',
    order_index: 2,
    locale: 'en',
    question_text: 'I find myself needing constant reassurance that my partner really loves me.',
    options: enOptions('ANX'),
  },
  {
    id: 'at-en-03',
    order_index: 3,
    locale: 'en',
    question_text: 'When my partner is slow to reply, I can think of little else until I hear back.',
    options: enOptions('ANX'),
  },
  {
    id: 'at-en-04',
    order_index: 4,
    locale: 'en',
    question_text: 'I over-analyze the tone and wording of my partner’s texts.',
    options: enOptions('ANX'),
  },
  {
    id: 'at-en-05',
    order_index: 5,
    locale: 'en',
    question_text: 'It often feels like I care about my partner more than they care about me.',
    options: enOptions('ANX'),
  },
  {
    id: 'at-en-06',
    order_index: 6,
    locale: 'en',
    question_text: 'I get jealous easily when my partner pays attention to someone else.',
    options: enOptions('ANX'),
  },
  {
    id: 'at-en-07',
    order_index: 7,
    locale: 'en',
    question_text: 'When I’m alone, I worry that something might be wrong with the relationship.',
    options: enOptions('ANX'),
  },
  {
    id: 'at-en-08',
    order_index: 8,
    locale: 'en',
    question_text: 'Even a small argument makes me afraid the relationship might be over.',
    options: enOptions('ANX'),
  },
  {
    id: 'at-en-09',
    order_index: 9,
    locale: 'en',
    question_text: 'Getting too close to a partner makes me feel uncomfortable or smothered.',
    options: enOptions('AVO'),
  },
  {
    id: 'at-en-10',
    order_index: 10,
    locale: 'en',
    question_text: 'When things start getting serious, I tend to pull away.',
    options: enOptions('AVO'),
  },
  {
    id: 'at-en-11',
    order_index: 11,
    locale: 'en',
    question_text: 'It’s hard for me to open up or show my vulnerable side to a partner.',
    options: enOptions('AVO'),
  },
  {
    id: 'at-en-12',
    order_index: 12,
    locale: 'en',
    question_text: 'Even in a relationship, I really need my own independent time and space.',
    options: enOptions('AVO'),
  },
  {
    id: 'at-en-13',
    order_index: 13,
    locale: 'en',
    question_text: 'I’d rather handle things on my own than depend on someone else.',
    options: enOptions('AVO'),
  },
  {
    id: 'at-en-14',
    order_index: 14,
    locale: 'en',
    question_text: 'When a partner asks for too much emotionally, I want to take a step back.',
    options: enOptions('AVO'),
  },
  {
    id: 'at-en-15',
    order_index: 15,
    locale: 'en',
    question_text: 'I prefer keeping things light rather than diving into deep emotional talks.',
    options: enOptions('AVO'),
  },
  {
    id: 'at-en-16',
    order_index: 16,
    locale: 'en',
    question_text: 'When a partner gets too involved in my daily life, I feel like I’m losing my freedom.',
    options: enOptions('AVO'),
  },
];
