/**
 * "Question painted on a wall" posts.
 *
 * The format that actually travels on Instagram is not a card floating
 * over a video — it is a photograph of a real wall with the puzzle
 * painted onto it and a person standing there reading it. This module
 * produces exactly that:
 *
 *   1. the WALL is generated once per pool entry by Gemini (photoreal,
 *      person seen strictly from behind, surface left deliberately blank)
 *      and parked in our own bucket — see murals.ts
 *   2. the QUESTION is drawn here as plain SVG and composited onto the
 *      wall with a blend mode, so the wall's own texture, shadows and
 *      lighting fall across the letters. `multiply` reads as dark paint
 *      soaking into a light wall, `screen` as whitewash or chalk.
 *
 * The text is never generated by the image model. Image models garble
 * letters and digits, and a garbled digit in a maths puzzle is a wrong
 * answer shipped to the audience — so the model only ever draws the
 * empty wall, and every glyph on it comes from our own renderer.
 */

import sharp from 'sharp';
import type { IgCard } from './ig-content';
import { recolorFigureSvg } from './shape-quizzes';
import { FOOTAGE_H, FOOTAGE_W } from './footage';

export type MuralStyleId = 'plaster' | 'school' | 'brick' | 'night' | 'blackboard';

export interface MuralStyle {
  id: MuralStyleId;
  /** Korean label for /admin/media. */
  label: string;
  /** Surface half of the generation prompt (the framing half is shared). */
  surface: string;
  /** Paint colour for headline, options and figures. */
  ink: string;
  /** Outline colour inside recoloured figures (cube edges). */
  outline: string;
  /** Marker colour for the "?" tile. */
  accent: string;
  blend: 'multiply' | 'screen';
  /** Top of the painted block, in FOOTAGE space (1512×2688). */
  textTop: number;
  /**
   * Where the painted block must stop — roughly where the person's head
   * starts in this style's shots. Paint below this and the question ends
   * up written across the subject instead of the wall.
   */
  blockBottom: number;
}

export const MURAL_STYLES: Record<MuralStyleId, MuralStyle> = {
  plaster: {
    id: 'plaster',
    label: '담쟁이 크림색 벽',
    surface:
      'The wall is a warm cream painted plaster wall of an old building, with a few green ' +
      'ivy vines trailing down from the top edge, soft afternoon sunlight.',
    ink: '#3A2F28',
    outline: '#F0E6D6',
    accent: '#B4451F',
    blend: 'multiply',
    textTop: 450,
    blockBottom: 1700,
  },
  school: {
    id: 'school',
    label: '학교 콘크리트 벽',
    surface:
      'The wall is a plain grey concrete school courtyard wall, bright overcast midday ' +
      'light, a few small dry leaves on the ground.',
    ink: '#2C2C2E',
    outline: '#E8E8EA',
    accent: '#9C3B1B',
    blend: 'multiply',
    textTop: 370,
    blockBottom: 1580,
  },
  brick: {
    id: 'brick',
    label: '붉은 벽돌 벽 (흰 페인트)',
    surface:
      'The wall is an old red-brick wall photographed dead-on and flat, warm ' +
      'late-afternoon sunlight raking across the brick texture.',
    ink: '#FBF6EA',
    outline: '#2A1A12',
    accent: '#FFD98A',
    blend: 'screen',
    textTop: 420,
    blockBottom: 1500,
  },
  night: {
    id: 'night',
    label: '야간 전구 벽',
    surface:
      'The wall is a smooth cream stucco exterior wall at night, lit by warm hanging ' +
      'string bulb lights along the top edge, cosy evening atmosphere.',
    ink: '#3E3128',
    outline: '#F2E4D2',
    accent: '#A9451C',
    blend: 'multiply',
    textTop: 450,
    blockBottom: 1530,
  },
  blackboard: {
    id: 'blackboard',
    label: '교실 칠판 (분필)',
    surface:
      'Interior classroom. A large dark green chalkboard covering the whole wall, clean ' +
      'and empty with a faint chalk-dust haze. A teacher in a simple shirt stands looking ' +
      'up at the empty board. Soft warm indoor light.',
    ink: '#F4F6F0',
    outline: '#16302A',
    accent: '#FFE9A8',
    blend: 'screen',
    textTop: 460,
    blockBottom: 1300,
  },
};

export const MURAL_STYLE_IDS = Object.keys(MURAL_STYLES) as MuralStyleId[];

/**
 * The framing half of the prompt — identical for every style so the pool
 * stays visually coherent. The negatives are load-bearing: without them
 * the model writes its own (garbled) text on the wall, and it has been
 * observed inventing a phone status bar and clock along the bottom edge.
 */
const FRAMING = [
  'Vertical 9:16 smartphone photo, documentary style, camera square-on and parallel to the',
  'flat surface with no perspective distortion. Shot from behind the subject at chest',
  'height. One person seen strictly FROM BEHIND — back of the head and shoulders only,',
  'face completely not visible — standing and looking up at the surface. The person is',
  'small, in the bottom third of the frame, slightly off-centre.',
  'CRITICAL: the surface must be completely BLANK and EMPTY — no text, no letters, no',
  'numbers, no writing, no chalk marks, no posters, no signs, no graffiti, no drawings.',
  'No phone UI, no status bar, no navigation bar, no timestamp, no watermark, no border.',
  'Photorealistic. No text anywhere in the image.',
].join(' ');

export function muralPrompt(style: MuralStyle): string {
  return `${FRAMING} ${style.surface}`;
}

// ---------------------------------------------------------------------------
// Generation (Gemini)
// ---------------------------------------------------------------------------

/**
 * Tried in order. The preview model produces the better wall but is not
 * guaranteed to be enabled on every key, so the flash model backs it up —
 * a pool that fills with slightly plainer walls beats a pool that stays
 * empty.
 */
const IMAGE_MODELS = ['gemini-3-pro-image', 'gemini-2.5-flash-image'];
const API_ROOT = 'https://generativelanguage.googleapis.com/v1beta/models';

export type GenerateResult =
  | { ok: true; image: Buffer; model: string }
  | { ok: false; reason: string };

/** Generate one wall photo for a style. Returns raw model output bytes. */
export async function generateMuralImage(args: {
  style: MuralStyle;
  apiKey: string;
  deadlineAt?: number;
}): Promise<GenerateResult> {
  const body = JSON.stringify({
    contents: [{ parts: [{ text: muralPrompt(args.style) }] }],
    generationConfig: {
      responseModalities: ['IMAGE'],
      imageConfig: { aspectRatio: '9:16' },
    },
  });

  const notes: string[] = [];
  for (const model of IMAGE_MODELS) {
    if (args.deadlineAt && Date.now() > args.deadlineAt) {
      return { ok: false, reason: `deadline_exceeded after: ${notes.join('; ')}` };
    }
    const budget = args.deadlineAt
      ? Math.min(120_000, Math.max(5_000, args.deadlineAt - Date.now()))
      : 120_000;
    try {
      const res = await fetch(`${API_ROOT}/${model}:generateContent`, {
        method: 'POST',
        headers: { 'x-goog-api-key': args.apiKey, 'Content-Type': 'application/json' },
        body,
        cache: 'no-store',
        signal: AbortSignal.timeout(budget),
      });
      const raw = (await res.json().catch(() => ({}))) as {
        candidates?: { content?: { parts?: { inlineData?: { data?: string } }[] } }[];
        error?: { message?: string; status?: string };
      };
      if (!res.ok || raw.error) {
        notes.push(`${model}: ${raw.error?.message ?? `http_${res.status}`}`);
        continue;
      }
      const part = raw.candidates?.[0]?.content?.parts?.find((p) => p.inlineData?.data);
      if (!part?.inlineData?.data) {
        notes.push(`${model}: no_image_in_response`);
        continue;
      }
      return { ok: true, image: Buffer.from(part.inlineData.data, 'base64'), model };
    } catch (err) {
      notes.push(`${model}: ${err instanceof Error ? err.message : 'fetch_failed'}`);
    }
  }
  return { ok: false, reason: notes.join('; ') || 'no_model_available' };
}

/** Normalise model output to the stored footage size. */
export async function normalizeMuralImage(image: Buffer): Promise<Buffer> {
  return sharp(image)
    .resize(FOOTAGE_W, FOOTAGE_H, { fit: 'cover', position: 'centre' })
    .jpeg({ quality: 88 })
    .toBuffer();
}

// ---------------------------------------------------------------------------
// The painted layer
// ---------------------------------------------------------------------------

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/**
 * Rough advance width in em. Hangul and CJK are full-width; Latin at
 * Pretendard's proportions averages a bit over half an em. Two classes
 * is crude but it is the difference between a Korean line and an English
 * line of the same character count differing by ~2× — which a plain
 * character budget gets badly wrong.
 */
function textWidthEm(text: string): number {
  let em = 0;
  for (const ch of text) em += /[ᄀ-ᇿ　-鿿가-힯＀-｠]/.test(ch) ? 1 : 0.56;
  return em;
}

/**
 * Greedy wrap to a maximum line width, measured in em.
 *
 * Breaking on spaces alone is not enough here: Korean routinely runs
 * long stretches with no space at all, and a single over-long token
 * would then sit on one line and run straight off both edges of the
 * wall. Anything wider than the box is therefore also broken between
 * characters, which is the normal line-breaking behaviour for Hangul
 * anyway.
 */
function wrapToWidth(text: string, maxEm: number): string[] {
  const lines: string[] = [];
  let line = '';

  const pushLine = () => {
    if (line) lines.push(line);
    line = '';
  };

  for (const word of text.split(/\s+/).filter(Boolean)) {
    const candidate = line ? `${line} ${word}` : word;
    if (textWidthEm(candidate) <= maxEm) {
      line = candidate;
      continue;
    }
    pushLine();
    if (textWidthEm(word) <= maxEm) {
      line = word;
      continue;
    }
    // Token wider than the whole box — break it between characters.
    for (const ch of word) {
      if (textWidthEm(line + ch) > maxEm && line) pushLine();
      line += ch;
    }
  }
  pushLine();
  return lines;
}

/**
 * Fit the whole question into the headline box by shrinking the type
 * until it fits — never by dropping words.
 *
 * The first cut of this truncated at three lines, which silently ate the
 * tail of every long prompt ("…One is MIRRORED. Which" — the "one is
 * it?" simply gone). A half-question is a broken post, so the only
 * variable allowed to give here is the font size; at the floor the text
 * wraps to as many lines as it needs and stays complete.
 */
export function fitHeadline(
  text: string,
  opts: { boxWidth: number; maxLines?: number } = { boxWidth: 1180 },
): { lines: string[]; size: number } {
  const maxLines = opts.maxLines ?? 4;
  const sizes = [100, 90, 80, 72, 64, 56];
  for (const size of sizes) {
    const lines = wrapToWidth(text, opts.boxWidth / size);
    if (lines.length <= maxLines) return { lines, size };
  }
  const size = sizes[sizes.length - 1];
  return { lines: wrapToWidth(text, opts.boxWidth / size), size };
}

/** Strip the outer <svg> wrapper so a figure can be nested in a <g>. */
function figureBody(svg: string): { body: string; vbW: number; vbH: number } | null {
  const vb = /viewBox="0 0 ([\d.]+) ([\d.]+)"/.exec(svg);
  const inner = /<svg[^>]*>([\s\S]*)<\/svg>/.exec(svg);
  if (!vb || !inner) return null;
  return { body: inner[1], vbW: Number(vb[1]), vbH: Number(vb[2]) };
}

/**
 * Whether a post can be painted onto a wall at all.
 *
 * The mural renderer is plain SVG, so it can carry the two shapes a wall
 * actually needs: a text question, or a self-contained `figure` (every
 * shape puzzle). The remaining scene kinds — road, sequence, bars — are
 * satori JSX components whose content IS the question (the numbers in a
 * sequence, the bars in a rate puzzle); painting only their prompt would
 * ship a post with the question missing. Those keep the card treatment.
 */
export function muralEligible(card: Pick<IgCard, 'scene'>): boolean {
  return !card.scene || card.scene.kind === 'figure';
}

/** The figure a card carries, if it carries one this renderer can paint. */
export function cardFigureSvg(card: Pick<IgCard, 'scene'>): string | undefined {
  return card.scene?.kind === 'figure' ? card.scene.svg : undefined;
}

/**
 * True when the options are pointers INTO the figure ("Shape A", "Shape
 * B") rather than answers in their own right ("13", "intermittent").
 *
 * The rotation and mirror families draw lettered tiles inside the figure
 * itself, so painting a second A–D list beneath it is noise. The numeric
 * families (squares, triangles, lines, cubes) carry their answers only
 * in the option list, and dropping it would ship a puzzle with nothing
 * to choose from — so the fallback when this is unsure must be to DRAW
 * the list, which is what returning false does.
 */
export function optionsAreFigureRefs(options: readonly { text: string }[]): boolean {
  return (
    options.length > 0 &&
    options.every((o) => /^\s*(shape|figure|option)\s+[A-D]\s*$/i.test(o.text))
  );
}

/**
 * The whole painted layer, in FOOTAGE space. Transparent everywhere the
 * paint is not — the caller composites it with the style's blend mode.
 */
export function muralOverlaySvg(args: {
  style: MuralStyle;
  card: Pick<IgCard, 'prompt' | 'options'>;
  /** Shape-puzzle figure, still in its authored white-on-transparent form. */
  figureSvg?: string;
  figureAspect?: number;
  handle?: string;
}): string {
  const { style, card } = args;
  const W = FOOTAGE_W;
  const cx = W / 2;
  const ink = style.ink;
  const top = style.textTop;

  const { lines: headline, size: headSize } = fitHeadline(card.prompt, {
    boxWidth: W - 260,
  });
  const headLead = Math.round(headSize * 1.22);
  const headBottom = top + headline.length * headLead;

  const heading = headline
    .map(
      (line, i) =>
        `<text x="${cx}" y="${top + (i + 1) * headLead}" text-anchor="middle" ` +
        `font-family="Pretendard, Noto Sans KR, sans-serif" font-weight="800" ` +
        `font-size="${headSize}" letter-spacing="-3" fill="${ink}">${esc(line)}</text>`,
    )
    .join('');

  const ruleY = headBottom + 34;
  const rule =
    `<path d="M ${cx - 280} ${ruleY} L ${cx + 280} ${ruleY - 6}" stroke="${ink}" ` +
    `stroke-width="11" stroke-linecap="round"/>`;

  // A running cursor, not fixed offsets: the block's height varies with
  // the headline's line count and with whether a figure is present, and
  // anything placed at a constant y (the handle, most visibly) ends up
  // drawn straight through the figure on the taller layouts.
  let cursor = ruleY;
  let bodyBlock = '';

  const fig = args.figureSvg ? figureBody(args.figureSvg) : null;
  const opts = card.options.slice(0, 4);
  const drawOptions = !fig || !optionsAreFigureRefs(opts);
  const optionRows = drawOptions ? Math.ceil(opts.length / 2) : 0;
  const OPTION_ROW_H = 190;
  const HANDLE_GAP = 90;

  if (fig) {
    const recolored = recolorFigureSvg(
      `<svg viewBox="0 0 ${fig.vbW} ${fig.vbH}">${fig.body}</svg>`,
      { ink, accent: style.accent, outline: style.outline },
    );
    const inner = figureBody(recolored)!;
    const y = cursor + 70;
    // Fit the figure to whatever wall is actually left after the option
    // rows and the handle have taken their share — scaling on width
    // alone runs the block down over the person's head on the shots
    // where the empty wall is short.
    const reserved = optionRows * OPTION_ROW_H + (drawOptions ? 74 : 0) + HANDLE_GAP;
    const availH = Math.max(220, style.blockBottom - y - reserved);
    const scale = Math.min((W - 340) / inner.vbW, availH / inner.vbH);
    const drawW = inner.vbW * scale;
    bodyBlock +=
      `<g transform="translate(${((W - drawW) / 2).toFixed(1)} ${y}) scale(${scale.toFixed(4)})">` +
      `${inner.body}</g>`;
    cursor = y + inner.vbH * scale;
  }

  if (drawOptions) {
    const letters = ['A', 'B', 'C', 'D'];
    const rowTop = cursor + (fig ? 74 : 96);
    const rows = optionRows;
    const colX = [cx - 380, cx + 60];
    bodyBlock += opts
      .map((opt, i) => {
        const x = colX[i % 2];
        const y = rowTop + Math.floor(i / 2) * OPTION_ROW_H;
        return (
          `<circle cx="${x + 48}" cy="${y + 38}" r="46" fill="none" stroke="${ink}" stroke-width="8"/>` +
          `<text x="${x + 48}" y="${y + 60}" text-anchor="middle" ` +
          `font-family="Pretendard, Noto Sans KR, sans-serif" font-weight="800" font-size="52" ` +
          `fill="${ink}">${letters[i]}</text>` +
          `<text x="${x + 122}" y="${y + 60}" font-family="Pretendard, Noto Sans KR, sans-serif" ` +
          `font-weight="700" font-size="52" letter-spacing="-1" fill="${ink}">${esc(opt.text)}</text>`
        );
      })
      .join('');
    cursor = rowTop + rows * OPTION_ROW_H;
  }

  // The handle goes under the block, or nowhere. Clamping it upward (the
  // obvious-looking fix) drags it back INTO the figure, which is exactly
  // the collision it is meant to avoid — so when the wall has run out,
  // the handle is simply dropped.
  const handleY = cursor + HANDLE_GAP;
  const handle =
    args.handle && handleY <= style.blockBottom
      ? `<text x="${cx}" y="${handleY.toFixed(0)}" text-anchor="middle" ` +
      `font-family="Pretendard, Noto Sans KR, sans-serif" font-weight="600" font-size="42" ` +
      `letter-spacing="1.5" fill="${ink}" opacity="0.5">${esc(args.handle)}</text>`
    : '';

  // A hair of rotation keeps it from reading as a digital sticker.
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${FOOTAGE_H}" viewBox="0 0 ${W} ${FOOTAGE_H}">
  <g transform="rotate(-0.4 ${cx} ${top + 200})">${heading}${rule}${bodyBlock}${handle}</g>
</svg>`;
}

/**
 * Paint the question onto a wall photo. The paint is applied at footage
 * resolution BEFORE any Ken Burns crop, so the letters travel with the
 * wall instead of floating over it.
 */
export async function paintMural(args: {
  wall: Buffer;
  style: MuralStyle;
  card: Pick<IgCard, 'prompt' | 'options' | 'scene'>;
  handle?: string;
}): Promise<Buffer> {
  const overlay = Buffer.from(
    muralOverlaySvg({
      style: args.style,
      card: args.card,
      figureSvg: cardFigureSvg(args.card),
      handle: args.handle,
    }),
  );
  return sharp(args.wall)
    .resize(FOOTAGE_W, FOOTAGE_H, { fit: 'cover', position: 'centre' })
    .composite([{ input: overlay, top: 0, left: 0, blend: args.style.blend }])
    .png()
    .toBuffer();
}
