import type { Question } from './types';

export const dummyEnQuestions: Question[] = [
  // ───── Verbal (8) ─────
  {
    id: 'en-001',
    order_index: 1,
    category: 'verbal',
    difficulty: 1,
    locale: 'en',
    question_text: 'Which one does NOT belong with the others?',
    options: [
      { id: 'A', text: 'Apple' },
      { id: 'B', text: 'Pear' },
      { id: 'C', text: 'Carrot' },
      { id: 'D', text: 'Grape' },
    ],
    correct_id: 'C',
    explanation: 'Carrot is a vegetable; the others are fruits.',
  },
  {
    id: 'en-002',
    order_index: 2,
    category: 'verbal',
    difficulty: 2,
    locale: 'en',
    question_text: 'Which word is closest in meaning to "joyful"?',
    options: [
      { id: 'A', text: 'sad' },
      { id: 'B', text: 'delighted' },
      { id: 'C', text: 'angry' },
      { id: 'D', text: 'surprised' },
    ],
    correct_id: 'B',
    explanation: '"Delighted" is the closest synonym for "joyful".',
  },
  {
    id: 'en-003',
    order_index: 3,
    category: 'verbal',
    difficulty: 2,
    locale: 'en',
    question_text: 'What is the opposite of "wide"?',
    options: [
      { id: 'A', text: 'narrow' },
      { id: 'B', text: 'long' },
      { id: 'C', text: 'tall' },
      { id: 'D', text: 'deep' },
    ],
    correct_id: 'A',
    explanation: 'The antonym of "wide" is "narrow".',
  },
  {
    id: 'en-004',
    order_index: 4,
    category: 'verbal',
    difficulty: 2,
    locale: 'en',
    question_text: 'Which is NOT a piece of furniture?',
    options: [
      { id: 'A', text: 'chair' },
      { id: 'B', text: 'desk' },
      { id: 'C', text: 'bed' },
      { id: 'D', text: 'pencil' },
    ],
    correct_id: 'D',
    explanation: 'A pencil is a writing tool; the others are furniture.',
  },
  {
    id: 'en-005',
    order_index: 5,
    category: 'verbal',
    difficulty: 3,
    locale: 'en',
    question_text: 'Doctor : Hospital = Teacher : ?',
    options: [
      { id: 'A', text: 'Student' },
      { id: 'B', text: 'School' },
      { id: 'C', text: 'Textbook' },
      { id: 'D', text: 'Lesson' },
    ],
    correct_id: 'B',
    explanation:
      'The pattern is profession-to-workplace. A doctor works at a hospital; a teacher works at a school. Students, lessons, and textbooks are all elements within a school but do not match the "workplace" relation.',
  },
  {
    id: 'en-006',
    order_index: 6,
    category: 'verbal',
    difficulty: 3,
    locale: 'en',
    question_text: 'Foot : Sock = Hand : ?',
    options: [
      { id: 'A', text: 'shoe' },
      { id: 'B', text: 'glove' },
      { id: 'C', text: 'hat' },
      { id: 'D', text: 'watch' },
    ],
    correct_id: 'B',
    explanation: 'A sock covers the foot; a glove covers the hand.',
  },
  {
    id: 'en-007',
    order_index: 7,
    category: 'verbal',
    difficulty: 4,
    locale: 'en',
    question_text: 'Which word has a meaning different from the others?',
    options: [
      { id: 'A', text: 'enormous' },
      { id: 'B', text: 'vast' },
      { id: 'C', text: 'tiny' },
      { id: 'D', text: 'massive' },
    ],
    correct_id: 'C',
    explanation: '"Tiny" means small; the others all mean "very large".',
  },
  {
    id: 'en-008',
    order_index: 8,
    category: 'verbal',
    difficulty: 4,
    locale: 'en',
    question_text: 'Pen : Writing = Brush : ?',
    options: [
      { id: 'A', text: 'paper' },
      { id: 'B', text: 'ink' },
      { id: 'C', text: 'painting' },
      { id: 'D', text: 'palette' },
    ],
    correct_id: 'C',
    explanation: 'A pen is used for writing; a brush is used for painting.',
  },

  // ───── Numerical (8) ─────
  {
    id: 'en-009',
    order_index: 9,
    category: 'numerical',
    difficulty: 1,
    locale: 'en',
    question_text: 'What number comes next?  2, 4, 6, 8, ?',
    options: [
      { id: 'A', text: '9' },
      { id: 'B', text: '10' },
      { id: 'C', text: '12' },
      { id: 'D', text: '14' },
    ],
    correct_id: 'B',
    explanation: 'Arithmetic progression of +2. 8 + 2 = 10.',
  },
  {
    id: 'en-010',
    order_index: 10,
    category: 'numerical',
    difficulty: 2,
    locale: 'en',
    question_text: 'What number comes next?  3, 6, 12, 24, ?',
    options: [
      { id: 'A', text: '36' },
      { id: 'B', text: '42' },
      { id: 'C', text: '48' },
      { id: 'D', text: '60' },
    ],
    correct_id: 'C',
    explanation: 'Geometric progression of ×2. 24 × 2 = 48.',
  },
  {
    id: 'en-011',
    order_index: 11,
    category: 'numerical',
    difficulty: 2,
    locale: 'en',
    question_text: 'If 3 apples cost $1.20, how much do 5 apples cost?',
    options: [
      { id: 'A', text: '$1.80' },
      { id: 'B', text: '$2.00' },
      { id: 'C', text: '$2.40' },
      { id: 'D', text: '$3.00' },
    ],
    correct_id: 'B',
    explanation: 'Each apple is $0.40. 5 × $0.40 = $2.00.',
  },
  {
    id: 'en-012',
    order_index: 12,
    category: 'numerical',
    difficulty: 3,
    locale: 'en',
    question_text: 'What number comes next?  1, 1, 2, 3, 5, 8, ?',
    options: [
      { id: 'A', text: '11' },
      { id: 'B', text: '13' },
      { id: 'C', text: '15' },
      { id: 'D', text: '21' },
    ],
    correct_id: 'B',
    explanation: 'Fibonacci sequence: each term is the sum of the two before. 5 + 8 = 13.',
  },
  {
    id: 'en-013',
    order_index: 13,
    category: 'numerical',
    difficulty: 3,
    locale: 'en',
    question_text: 'What number is missing?  1, 4, 9, 16, ?, 36',
    options: [
      { id: 'A', text: '20' },
      { id: 'B', text: '24' },
      { id: 'C', text: '25' },
      { id: 'D', text: '32' },
    ],
    correct_id: 'C',
    explanation: 'Perfect squares: 1², 2², 3², 4², 5², 6². Missing: 5² = 25.',
  },
  {
    id: 'en-014',
    order_index: 14,
    category: 'numerical',
    difficulty: 4,
    locale: 'en',
    question_text: 'What number comes next?  2, 5, 11, 23, ?',
    options: [
      { id: 'A', text: '35' },
      { id: 'B', text: '41' },
      { id: 'C', text: '46' },
      { id: 'D', text: '47' },
    ],
    correct_id: 'D',
    explanation: 'Each term equals the previous × 2 + 1. 23 × 2 + 1 = 47.',
  },
  {
    id: 'en-015',
    order_index: 15,
    category: 'numerical',
    difficulty: 4,
    locale: 'en',
    question_text: 'What is the average of 4, 7, and 11?',
    options: [
      { id: 'A', text: '7' },
      { id: 'B', text: '7.3' },
      { id: 'C', text: '7.5' },
      { id: 'D', text: '8' },
    ],
    correct_id: 'B',
    explanation: '(4 + 7 + 11) / 3 = 22 / 3 ≈ 7.3.',
  },
  {
    id: 'en-016',
    order_index: 16,
    category: 'numerical',
    difficulty: 5,
    locale: 'en',
    question_text:
      'On a clock at exactly 3:00, what is the angle between the hour and minute hands?',
    options: [
      { id: 'A', text: '60°' },
      { id: 'B', text: '75°' },
      { id: 'C', text: '90°' },
      { id: 'D', text: '120°' },
    ],
    correct_id: 'C',
    explanation: '360° / 12 = 30° per hour mark. 3 marks apart = 90°.',
  },

  // ───── Spatial (7) ─────
  {
    id: 'en-017',
    order_index: 17,
    category: 'spatial',
    difficulty: 2,
    locale: 'en',
    figure_id: 'cube-net-cross',
    question_text:
      'The cross-shaped net below folds into a cube. How many pairs of opposite faces does the cube have?',
    options: [
      { id: 'A', text: '2' },
      { id: 'B', text: '3' },
      { id: 'C', text: '4' },
      { id: 'D', text: '6' },
    ],
    correct_id: 'B',
    explanation: 'A cube has 6 faces arranged in 3 opposing pairs.',
  },
  {
    id: 'en-018',
    order_index: 18,
    category: 'spatial',
    difficulty: 3,
    locale: 'en',
    figure_id: 'f-upright',
    question_text: 'Which figure shows the letter below rotated 90° clockwise?',
    options: [
      { id: 'A', figure_id: 'f-rot90' },
      { id: 'B', figure_id: 'f-rot180' },
      { id: 'C', figure_id: 'f-rot270' },
      { id: 'D', figure_id: 'f-mirror' },
    ],
    correct_id: 'A',
    explanation: 'Rotating "F" 90° clockwise puts the top of the F on the right.',
  },
  {
    id: 'en-019',
    order_index: 19,
    category: 'spatial',
    difficulty: 3,
    locale: 'en',
    question_text:
      'On a die, 1 is opposite 6, 2 is opposite 5, and 3 is opposite 4. If 1, 2, and 3 are visible, what is the sum of the three hidden faces?',
    options: [
      { id: 'A', text: '9' },
      { id: 'B', text: '12' },
      { id: 'C', text: '15' },
      { id: 'D', text: '18' },
    ],
    correct_id: 'C',
    explanation: 'The hidden faces are 6, 5, and 4. 6 + 5 + 4 = 15.',
  },
  {
    id: 'en-020',
    order_index: 20,
    category: 'spatial',
    difficulty: 3,
    locale: 'en',
    figure_id: 'f-upright',
    question_text: 'Which figure shows the mirror image (left-right flip) of the letter below?',
    options: [
      { id: 'A', figure_id: 'f-mirror' },
      { id: 'B', figure_id: 'f-rot180' },
      { id: 'C', figure_id: 'f-rot90' },
      { id: 'D', figure_id: 'f-rot270' },
    ],
    correct_id: 'A',
    explanation:
      'A mirror image is a horizontal flip — distinct from a rotation (180° or 90°).',
  },
  {
    id: 'en-021',
    order_index: 21,
    category: 'spatial',
    difficulty: 4,
    locale: 'en',
    question_text:
      'A piece of paper is folded once horizontally and then once vertically. When unfolded, how many crease lines are there?',
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '2' },
      { id: 'C', text: '3' },
      { id: 'D', text: '4' },
    ],
    correct_id: 'B',
    explanation: 'One horizontal crease and one vertical crease = 2 lines total.',
  },
  {
    id: 'en-022',
    order_index: 22,
    category: 'spatial',
    difficulty: 4,
    locale: 'en',
    figure_id: 'pyramid-3step',
    question_text:
      'The figure below is a 3-step pyramid built from 1 cm cubes. How many cubes are there in total?',
    options: [
      { id: 'A', text: '9' },
      { id: 'B', text: '12' },
      { id: 'C', text: '14' },
      { id: 'D', text: '27' },
    ],
    correct_id: 'C',
    explanation: 'Step 1 (1) + Step 2 (4) + Step 3 (9) = 14 cubes.',
  },
  {
    id: 'en-023',
    order_index: 23,
    category: 'spatial',
    difficulty: 5,
    locale: 'en',
    figure_id: 'painted-cube',
    question_text:
      'A 3 cm cube is painted on all outer faces, then sliced into 1 cm cubes. How many small cubes have exactly three painted faces?',
    options: [
      { id: 'A', text: '4' },
      { id: 'B', text: '6' },
      { id: 'C', text: '8' },
      { id: 'D', text: '12' },
    ],
    correct_id: 'C',
    explanation: 'Only corner cubes have 3 painted faces; a cube has 8 corners.',
  },

  // ───── Logical (7) ─────
  {
    id: 'en-024',
    order_index: 24,
    category: 'logical',
    difficulty: 2,
    locale: 'en',
    question_text:
      'All students carry a backpack. Sam is a student. Therefore?',
    options: [
      { id: 'A', text: 'Sam carries a backpack.' },
      { id: 'B', text: 'Sam does not have a backpack.' },
      { id: 'C', text: 'Sam is not a student.' },
      { id: 'D', text: 'Cannot be determined.' },
    ],
    correct_id: 'A',
    explanation: 'Classic syllogism — if the premises are true, the conclusion follows.',
  },
  {
    id: 'en-025',
    order_index: 25,
    category: 'logical',
    difficulty: 3,
    locale: 'en',
    question_text: 'If it rains, I use an umbrella. I am not using an umbrella. Therefore?',
    options: [
      { id: 'A', text: 'It is raining.' },
      { id: 'B', text: 'It is not raining.' },
      { id: 'C', text: 'It will rain soon.' },
      { id: 'D', text: 'Cannot be determined.' },
    ],
    correct_id: 'B',
    explanation: 'Modus tollens: denying the consequent denies the antecedent.',
  },
  {
    id: 'en-026',
    order_index: 26,
    category: 'logical',
    difficulty: 3,
    locale: 'en',
    question_text:
      'A is taller than B. B is taller than C. C is taller than D. Who is the shortest?',
    options: [
      { id: 'A', text: 'A' },
      { id: 'B', text: 'B' },
      { id: 'C', text: 'C' },
      { id: 'D', text: 'D' },
    ],
    correct_id: 'D',
    explanation: 'A > B > C > D, so D is the shortest.',
  },
  {
    id: 'en-027',
    order_index: 27,
    category: 'logical',
    difficulty: 4,
    locale: 'en',
    question_text:
      'If yesterday was Tuesday, what day will the day after tomorrow be?',
    options: [
      { id: 'A', text: 'Thursday' },
      { id: 'B', text: 'Friday' },
      { id: 'C', text: 'Saturday' },
      { id: 'D', text: 'Sunday' },
    ],
    correct_id: 'B',
    explanation: 'Yesterday Tue → today Wed → tomorrow Thu → day after = Friday.',
  },
  {
    id: 'en-028',
    order_index: 28,
    category: 'logical',
    difficulty: 4,
    locale: 'en',
    question_text: 'Which one does NOT belong with the others?',
    options: [
      { id: 'A', text: 'Lion' },
      { id: 'B', text: 'Tiger' },
      { id: 'C', text: 'Leopard' },
      { id: 'D', text: 'Rabbit' },
    ],
    correct_id: 'D',
    explanation: 'Lion, tiger, and leopard are big cats; rabbit is not a feline.',
  },
  {
    id: 'en-029',
    order_index: 29,
    category: 'logical',
    difficulty: 5,
    locale: 'en',
    question_text:
      'Five people stand in a line. A is in front of B. C is in front of A. D is in front of C. E is at the very back. Who is at the very front?',
    options: [
      { id: 'A', text: 'A' },
      { id: 'B', text: 'C' },
      { id: 'C', text: 'D' },
      { id: 'D', text: 'E' },
    ],
    correct_id: 'C',
    explanation: 'Order from front to back: D — C — A — B — E. D is at the front.',
  },
  {
    id: 'en-030',
    order_index: 30,
    category: 'logical',
    difficulty: 5,
    locale: 'en',
    question_text:
      'On an island, truth-tellers always tell the truth and liars always lie. You ask one person, "Are you a truth-teller?" The person says "Yes". What can you conclude?',
    options: [
      { id: 'A', text: 'They must be a truth-teller.' },
      { id: 'B', text: 'They must be a liar.' },
      { id: 'C', text: 'They could be either.' },
      { id: 'D', text: 'Cannot be determined.' },
    ],
    correct_id: 'C',
    explanation:
      'A truth-teller answers "Yes" truthfully. A liar also answers "Yes" because they lie about being a liar. Both possible.',
  },
];
